### ISSUE TITLE
Migration des données de l'API

### ISSUE THREAD

**Issue by Aeliondw** [EpitechNice/EPITECH-Soul-Connection#2]
**Migration des données de l'API dans notre propre base de données que l'on pourra ainsi modifier dans notre application**

- [x]  Réaliser un schéma de notre base de données dans notre application afin d'harmoniser les données pré-existantes
- [x]  Se connecter à l'API et récupérer les données pré-existantes
- [ ]  Les données de l'API étant toujours mis à jour, mettre en place une mise à jour récurente pour récupérer ces données et mettre à jour notre base de données en conséquence (transition et une intégration transparentes entre les données existantes et le nouveau tableau de bord)

**Comment by Aeliondw** [comment]
- [ ] À corriger : les dates fetch de l'api sont les mêmes pour les employees (birth_place)

**Comment by Tech0ne** [comment]
This is now done through the soul-connection-fetch container, run using docker compose.
